# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages
RUN pip install grpcio grpcio-tools

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. analysis.proto


# Make port 50051 available to the world outside this container
EXPOSE 50052

# Run app.py when the container launches
CMD ["python", "analysis_service.py"]
