# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_reader.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11text_reader.proto\x12\ntextreader\"\x11\n\x0fTextReadRequest\" \n\x10TextReadResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2Z\n\x11TextReaderService\x12\x45\n\x08ReadText\x12\x1b.textreader.TextReadRequest\x1a\x1c.textreader.TextReadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_reader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREADREQUEST']._serialized_start=33
  _globals['_TEXTREADREQUEST']._serialized_end=50
  _globals['_TEXTREADRESPONSE']._serialized_start=52
  _globals['_TEXTREADRESPONSE']._serialized_end=84
  _globals['_TEXTREADERSERVICE']._serialized_start=86
  _globals['_TEXTREADERSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
