# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install grpcio grpcio-tools Flask redis 

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. storage.proto


# Make port 50051 available to the world outside this container
EXPOSE 50053

# Run app.py when the container launches
CMD ["python", "storage_service.py"]
